# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 15:53
from __future__ import unicode_literals

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndexMediaCarrousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrousel_title', models.CharField(max_length=200, verbose_name='Titulo carrousel')),
                ('carrousel_substitle', models.CharField(max_length=200, verbose_name='Substitulo carrousel')),
                ('carrousel_image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Carrousel')),
                ('slide_active', models.BooleanField(default=False, verbose_name='Ativo')),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('user_add', models.CharField(blank=True, max_length=100, null=True, verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='IndexMediaCircle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circle_title', models.CharField(max_length=200, verbose_name='Titulo circulo')),
                ('circle_substitle', models.CharField(max_length=200, verbose_name='Substitulo circulo')),
                ('circle_image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Imagem circulo')),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('user_add', models.CharField(blank=True, max_length=100, null=True, verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='IndexMediaPhotoFeatured',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_featured_title', models.CharField(max_length=200, verbose_name='Titulo imagem destaque')),
                ('photo_featured_title_silver', models.CharField(default='', max_length=200, verbose_name='Titulo cinza')),
                ('photo_featured_substitle', models.CharField(max_length=200, verbose_name='Substitulo imagem destaque')),
                ('photo_featured_image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Foto destaque')),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('user_add', models.CharField(blank=True, max_length=100, null=True, verbose_name='Usuario')),
            ],
        ),
    ]
