# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-08 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleonice', '0006_auto_20160208_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_name',
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default='TESTE', max_length=200),
            preserve_default=False,
        ),
    ]
