# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 02:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleonice', '0016_auto_20160219_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexmediacarrousel',
            name='slide_active',
            field=models.BooleanField(default=False),
        ),
    ]
