# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleonice', '0020_indexmediacarrousel_slide_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexmediaphotofeatured',
            name='photo_featured_title_silver',
            field=models.CharField(default='', max_length=200, verbose_name='Titulo cinza'),
        ),
    ]
