# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-08 20:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cleonice', '0008_auto_20160208_1850'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
