# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-08 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cleonice', '0009_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='Nome')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('product_type', models.CharField(choices=[('BO', 'Bolo'), ('BI', 'Biscoito')], default='BO', max_length=2)),
            ],
        ),
    ]
