# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 00:28
from __future__ import unicode_literals

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleonice', '0012_auto_20160216_2030'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexMediaConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrousel_title', models.CharField(max_length=200, verbose_name='Titulo carrousel')),
                ('carrousel_substitle', models.CharField(max_length=200, verbose_name='Substitulo carrousel')),
                ('carrousel', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Carrousel')),
                ('circle_title', models.CharField(max_length=200, verbose_name='Titulo circulo')),
                ('circle_substitle', models.CharField(max_length=200, verbose_name='Substitulo circulo')),
                ('circle', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Imagem circulo')),
                ('photo_featured_title', models.CharField(max_length=200, verbose_name='Titulo imagem destaque')),
                ('photo_featured_substitle', models.CharField(max_length=200, verbose_name='Substitulo imagem destaque')),
                ('photo_featured', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Foto destaque')),
                ('published_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
