# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 01:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleonice', '0014_auto_20160219_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexmediacarrousel',
            name='orderSlide',
            field=models.CharField(choices=[('FS', 'first-slide'), ('SS', 'second-slide'), ('TS', 'third-slide')], default='FS', max_length=2, unique=True, verbose_name='Ordem slide'),
            preserve_default=False,
        ),
    ]
