# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 01:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cleonice', '0015_indexmediacarrousel_orderslide'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indexmediacarrousel',
            old_name='orderSlide',
            new_name='order_slide',
        ),
    ]
