# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleonice', '0019_auto_20160220_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexmediacarrousel',
            name='slide_active',
            field=models.BooleanField(default=False, verbose_name='Ativo'),
        ),
    ]
