# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='indenficador baseado no titulo', max_length=100, unique=True, verbose_name='Identificador'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(help_text='identificador baseado no titulo', max_length=100, unique=True, verbose_name='Identificador'),
        ),
    ]
